version: '2.1'

services:
  vtv-giai-tri-grabber:
    image: vtv-giai-tri-grabber
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js